# Generated by Django 3.2.7 on 2021-09-15 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=64)),
                ('semester', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('max_seat', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ayaya', max_length=50)),
                ('img', models.ImageField(default='/images/a.jpg', upload_to='images/uploads')),
                ('subject', models.ManyToManyField(blank=True, related_name='subject', to='register.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/images/a.jpg', null=True, upload_to='images/uploads')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
    ]
