name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        postgresql version: '11'
    - name: Run Django unit tests
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py makemigrations
        python3 manage.py migrate
        coverage run --source='.' manage.py test
        coverage report
 